[package]
name = "eve_slots"
edition = "2024.beta"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "f761a7f61abc770f0ef802d1fba626ed6c48a216" }

[environments]
testnet_stillness = "4c78adac"
